# Generated by Django 5.1.2 on 2024-11-02 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Emp_app', '0002_employee_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='custom_fields',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
